<div align="center">
<h1>Soal Praktikum Dasar Kecerdasan Artifisial</h1>
<h3>Modul 3: Pengenalan Library NumPy</h3>
</div>

### Tujuan Praktikum
- Memahami konsep dasar array multidimensi dan bagaimana NumPy dapat digunakan untuk memanipulasi data secara efisien.
- Menguasai penggunaan fungsi dan operasi dasar NumPy, seperti pembuatan array, reshaping, indexing, serta pengolahan statistik.
- Mengaplikasikan NumPy dalam pemecahan masalah numerik dan pemodelan data untuk keperluan kecerdasan buatan dan analisis data.

In [ ]:
print("") # Tuliskan nama lengkap anda
print("") # Tuliskan nim anda
print("") # Tuliskan nomor meja
print("IF-48-XX") # Tuliskan kelas anda
print("") # Tuliskan kode asprak anda

**Jangan lupa untuk selalu import Library NumPy memulai sesi baru (run time) atau script Python yang memerlukan penggunaan library NumPy.**

In [ ]:
import numpy as np

### 1. Definisi Array dan Array NumPy (`5`)

**a.** Lengkapi potongan kode di bawah ini untuk membuat list Python biasa dan array NumPy, kemudian bandingkan perbedaan tipe datanya.

In [ ]:
# Inisialisasi list Python biasa
list_python = None 

# Inisialisasi array NumPy
arr_numpy = None 

# Cek tipe variabel
print("Tipe list_python:", type(list_python))
print("Tipe arr_numpy:", type(arr_numpy))

*Test case* program

|**Input**|**Output**    |
|---------|--------------|
|         |'Tipe list_python: <class 'list'>'<br>'Tipe arr_numpy: <class 'numpy.ndarray'>'|

**b.** Buat program yang menerima input dari pengguna berupa daftar nilai suhu, kemudian bentuk list Python biasa dan array NumPy dari daftar tersebut.

In [ ]:
# Input dari user
suhu = input("Masukkan daftar suhu, pisahkan dengan koma: ").split(",")

# Masukkan data ke list Python biasa
list_suhu = None

# Masukkan data ke array NumPy
arr_suhu = None

# Tampilkan hasil
print("List Suhu:", list_suhu)
print("Array Suhu:", arr_suhu)

*Test case* program

|**Input**|**Output**    |
|---------|--------------|
|25,30,28,32|List Suhu: [25, 30, 28, 32]<br>Array Suhu: [25 30 28 32]|
|18,22,19|List Suhu: [18, 22, 19]<br>Array Suhu: [18 22 19]|

### 2. Atribut Array NumPy (`10`)

Lengkapilah kode berikut untuk memeriksa atribut-atribut dimensi, bentuk, ukuran, dan tipe data dari array NumPy yang telah dibuat. Tujuan dari tugas ini adalah memahami bagaimana mendapatkan dimensi, bentuk, ukuran, dan tipe data dari array NumPy.

In [ ]:
# Inisialisasi array NumPy
arr_numpy = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 100, 110, 120]])

# Periksa jumlah dimensi 

# Periksa bentuk array (shape)

# Periksa ukuran array (size)

# Periksa tipe data array (dtype)

print("Jumlah dimensi:", None)
print("Bentuk array:", None)
print("Ukuran array:", None)
print("Tipe data array:", None)

*Test case* program

|**Input**|**Output**    |
|---------|--------------|
|         |'Jumlah dimensi: 2'<br>'Bentuk array: (3, 4)'<br>'Ukuran array: 12'<br>'Tipe data array: int64'|

### 3. Deklarasi Array dengan NumPy (`10`)

**a.** Inisialisasikan sebuah array 2D 3x4 yang berisi nilai nol.

In [ ]:
#jawab disini

*Test case* program

|**Input**|**Output**    |
|---------|--------------|
|         |[[0. 0. 0. 0.]<br>[0. 0. 0. 0.]<br>[0. 0. 0. 0.]]|

**b.** Inisialisasikan sebuah array 3D 2x4x3 yang berisi nilai satu.

In [ ]:
# jawab disini

*Test case* program

|**Input**|**Output**    |
|---------|--------------|
|         |[[[1. 1. 1.]<br>  [1. 1. 1.]<br>  [1. 1. 1.]<br>  [1. 1. 1.]]<br><br> [[1. 1. 1.]<br>  [1. 1. 1.]<br>  [1. 1. 1.]<br>  [1. 1. 1.]]]|

**c.** Inisialisasikan sebuah array 1D berukuran 7 dengan nilai acak.

In [ ]:
# jawab disini

*Test case* program

|**Input**|**Output**    |
|---------|--------------|
|         |[0.42365123 0.18572945 0.62418763 0.91523678 0.33217854 0.78541236 0.54123698]<br>*Catatan: Angka akan tergenerate secara random*|

**d.** Inisialisasikan sebuah array 1D dengan range nilai dari 15 hingga 30.

In [ ]:
# jawab disini

*Test case* program

|**Input**|**Output**    |
|---------|--------------|
|         |[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]|

**e.** Inisialisasikan sebuah array 1D yang memiliki nilai yang terdistribusi merata antara 0 hingga 10 dengan 6 elemen </br> Tip: gunakan .linspace()

In [ ]:
#jawab disini

*Test case* program

|**Input**|**Output**    |
|---------|--------------|
|         |[ 0.  2.  4.  6.  8. 10.]|

**f.** Buatlah array 2D berukuran 4x2 dengan semua elemen diisi dengan angka 5

In [ ]:
#jawab disini

*Test case* program

|**Input**|**Output**    |
|---------|--------------|
|         |[[5 5]<br> [5 5]<br> [5 5]<br> [5 5]]|

**g.** Buatlah sebuah array 1D dengan 6 nilai acak antara 0 dan 1

In [ ]:
#jawab disini

*Test case* program

|**Input**|**Output**    |
|---------|--------------|
|         |[0.45123678 0.78965412 0.12365478 0.65478912 0.32145698 0.98765432]<br>*Catatan: Angka akan tergenerate secara random*|

**h.** Buatlah array 2D berukuran 4x4 yang berisi bilangan acak bulat antara 5 dan 20

In [ ]:
#jawab disini

*Test case* program

|**Input**|**Output**    |
|---------|--------------|
|         |[[12  8 15 19] <br>[7 14 11  6] <br>[18  9 13 16] <br>[10 17  5 20]]<br>*Catatan: Angka akan tergenerate secara random*|

**i.** Buatlah array 2D berukuran 4x4 yang isinya merupakan nilai dari penjumlahan indeks baris dan kolomnya

In [ ]:
# Buat function penjumlahan dari dua bilangan
def penjumlahan(None):
    return None

arr = None # Ganti None dengan sintaks deklarasi array yang sesuai

# Tampilkan array

*Test case* program

|**Input**|**Output**    |
|---------|--------------|
|         |[[0. 1. 2. 3.] <br>[1. 2. 3. 4.] <br>[2. 3. 4. 5.] <br>[3. 4. 5. 6.]]|

### 4. Penambahan Elemen Array (`5`)

**a.** Anda bekerja dengan data produk yang disimpan dalam array NumPy. Data ini terdiri dari nama-nama produk dari dua gudang berbeda. Tugas Anda adalah menggabungkan data dari kedua gudang tersebut ke dalam satu array.

In [ ]:
# Data dari gudang X dan gudang Y
gudang_X = np.array(['Laptop', 'Monitor', 'Keyboard'])
gudang_Y = np.array(['Mouse', 'Printer', 'Scanner'])

# Gabungkan kedua array 

# Tampilkan array hasil gabungan

*Test case* program

|**Input**|**Output**    |
|---------|--------------|
|         |['Laptop' 'Monitor' 'Keyboard' 'Mouse' 'Printer' 'Scanner']|

**b.** Dua tim penjualan memerlukan penggabungan data target untuk analisis lebih lanjut. Target kedua tim tersebut disimpan dalam array terpisah. Gabungkan kedua array ini menjadi satu. **Gunakan sintaks penggabungan array yang berbeda dengan soal sebelumnya.**

In [ ]:
# Target tim Alpha dan Beta
target_alpha = np.array([150, 200, 175])
target_beta = np.array([180, 220, 195])

# Gabungkan kedua array 

# Tampilkan array hasil gabungan

*Test case* program

|**Input**|**Output**    |
|---------|--------------|
|         |[150 200 175 180 220 195]|

**c.** Anda diminta untuk menambahkan data penjualan bulan ke-4 pada posisi tertentu dalam array penjualan bulanan.

In [ ]:
# Penjualan bulanan
penjualan = np.array([450, 520, 610])

# Sisipkan penjualan bulan ke-4 (475) di posisi ke-1
# Tampilkan array setelah penyisipan

*Test case* program

|**Input**|**Output**    |
|---------|--------------|
|         |[450 475 520 610]|

**d.** Anda diminta untuk menggabungkan dua array harga ke dalam sebuah array 2D untuk mempermudah analisis lebih lanjut. Usahakan gunakan sintaks penggabungan array yang berbeda dengan soal sebelumnya.

In [ ]:
# Harga dari dua kategori
harga_elektronik = np.array([2500, 3500, 4200])
harga_furniture = np.array([1800, 2200, 2900])

# Gabungkan menjadi array 2D 
# Tampilkan array 2D hasil penggabungan

*Test case* program

|**Input**|**Output**    |
|---------|--------------|
|         |[[2500 3500 4200]<br> [1800 2200 2900]]|

### 5. Penghapusan Elemen Array (`10`)

**a.** Seorang admin inventory ingin membersihkan data yang mengandung elemen salah dalam sebuah array 1D yang berisi jumlah stok produk. Hapus elemen sesuai dengan index input si admin.

In [ ]:
# Array berisi jumlah stok produk
stok_produk = np.array([25, 42, 18, 35])

# Hapus elemen di indeks yang sesuai
# Tampilkan array setelah penghapusan elemen

*Test case* program

|**Input**|**Output**    |
|---------|--------------|
|2|[25 42 35]|
|0|[42 18 35]|

**b.** Anda bekerja dengan data penjualan dari beberapa toko yang disimpan dalam array 2D. Namun, data dari toko ke-2 dan semua produk kedua harus dihapus karena salah pencatatan. Hapus baris kedua dan kolom kedua dari array tersebut.

In [ ]:
# Data penjualan (dalam 2D array)
data_penjualan = np.array([[120, 150, 180],
                          [90, 110, 130],
                          [200, 180, 220],
                          [170, 190, 210]])

print("Masukkan nomor toko dan urutan produk, dengan dipisahkan oleh koma (,)")

# Simpan nomor toko (baris) dan urutan produk (kolom) dalam list

# Hapus data sesuai dengan target hapus

#Tampilkan array setelah penghapusan data

*Test case* program

|**Input**|**Output**    |
|---------|--------------|
|2,2|[[120 180]<br>[90 130]<br>[170 210]]|
|1,3|[[150 180]<br>[180 220]<br>[190 210]]|

**c.** Seorang analis ingin menghapus semua elemen yang berada di atas batas nilai dalam array yang berisi data transaksi.

In [ ]:
# Data transaksi
transaksi = np.array([50, 120, 80, 200, 95, 150])

# Menerima input batas nilai

# Menghapus elemen diatas batas nilai dari array

#Tampilkan array setelah penghapusan elemen

*Test case* program

|**Input**|**Output**    |
|---------|--------------|
|100|[50. 80. 95.]|
|150|[50. 120. 80. 95. 150.]|

### 6. Pengurutan Elemen Array (`5`)

**a.** Seorang kasir ingin menyusun total belanja pelanggan yang sudah diinput ke dalam sistem.

In [ ]:
# Data total belanja
total_belanja = np.array([85000, 120000, 45000, 95000, 72000])

# Urutkan total belanja

# Tampilkan array setelah pengurutan

*Test case* program

|**Input**|**Output**    |
|---------|--------------|
|         |[45000 72000 85000 95000 120000]|

**b.** Anda memiliki data performa karyawan dalam array 2D, di mana setiap baris adalah nilai KPI dari satu karyawan.

In [ ]:
# Data KPI karyawan
kpi_karyawan = np.array([[78, 85, 72], [90, 82, 88], [65, 70, 75]])

# Urutkan KPI setiap karyawan

# Tampilkan KPI yang sudah diurutkan

*Test case* program

|**Input**|**Output**    |
|---------|--------------|
|         |[[72 78 85]<br> [82 88 90]<br> [65 70 75]]|

**c.** Tim finance ingin mengurutkan semua data dalam array multidimensi berdasarkan nilainya (secara keseluruhan, bukan hanya per baris atau kolom).

In [ ]:
# Data keuangan
keuangan = np.array([[15, 8, 12], [5, 11, 3]])

# Urutkan semua elemen menjadi 1 array

# Tampilkan data yang sudah diurutkan

*Test case* program

|**Input**|**Output**    |
|---------|--------------|
|         |[3 5 8 11 12 15]|

### 7. Indexing dan Slicing Array (`10`)

**a.** Seorang analis memiliki data penjualan harian selama satu bulan dalam bentuk array (30 hari).</br> Analis ingin mengetahui penjualan pada hari ke-3, hari ke-12, hari ke-20, dan hari ke-28. Setelah mendapatkan nilai tersebut, lakukan perhitungan rata-rata.

In [ ]:
# Data penjualan selama 30 hari dengan range penjualan 100 sampai 500 (buat menggunakan inisialisasi random integer)
penjualan = None

# Ambil penjualan pada hari ke-3, 12, 20, dan 28

# Hitung rata-rata penjualan

print(f"Penjualan hari tertentu: {None}")
print(f"Rata-rata: {None}")

*Test case* program

|**Input**|**Output**    |
|---------|--------------|
|         |Penjualan hari tertentu: [245 312 178 421]<br>Rata-rata: 289.0<br>*Catatan: Angka akan tergenerate secara random*|

**b.** Seorang trainer mencatat jumlah pengunjung gym selama 12 hari dalam sebuah array. Namun, ia hanya ingin mengambil data pengunjung setiap 3 hari (hari ke-1, 4, 7, dan seterusnya) dan menghitung total pengunjungnya.

In [ ]:
# Data pengunjung gym selama 12 hari
pengunjung_gym = np.array([45, 52, 38, 61, 55, 42, 70, 48, 59, 63, 51, 67])

# Ambil data setiap 3 hari

# Hitung total pengunjung

# Tampilkan hasil sesuai contoh output

*Test case* program

|**Input**|**Output**    |
|---------|--------------|
|         |Data pengunjung: [45 61 70 63]<br>Total pengunjung: 239|

**c.** Anda memiliki array berisi data rating produk di marketplace. Anda ingin menghapus semua produk yang ratingnya kurang dari 4.0, kemudian hitung rata-rata rating produk yang tersisa. Gunakan boolean indexing untuk menyaring data dan hitung rata-ratanya.

In [ ]:
# Data rating produk
rating_produk = np.array([3.5, 4.2, 4.8, 3.2, 4.5, 2.9, 4.1, 3.8, 4.9, 4.0])

# Filter produk dengan rating >= 4.0

# Hitung rata-rata rating tersisa

# Tampilkan hasil sesuai contoh output

*Test case* program

|**Input**|**Output**    |
|---------|--------------|
|         |Rating produk tersisa: [4.2 4.8 4.5 4.1 4.9 4. ]<br>Rata-rata rating tersisa: 4.42|

### 8. Penyalinan (Copy) Array (`5`)

**a.** Seorang data scientist ingin melakukan analisis terhadap data sensor dengan mengubah data aslinya. Buat salinan "shallow copy" dari array data asli, lalu ubah elemen tertentu pada indeks tertentu dari data yang telah disalin.

In [ ]:
# Data sensor asli
sensor_asli = np.array([22, 28, 35, 41, 50])

# Buat shallow copy
sensor_copy = None

# Masukkan indeks elemen yang ingin diubah dan data baru dengan dipisahkan dengan koma
info_perubahan = None

# Ubah sensor_copy pada indeks yang sesuai dengan data_baru
sensor_copy[None] = None

# Tampilkan sensor_copy dan sensor_asli
print("Sensor Copy:", sensor_copy)
print("Sensor Asli:", sensor_asli)

*Test case* program

|**Input**|**Output**    |
|---------|--------------|
|2,99|Sensor Copy: [22 28 99 41 50]<br>Sensor Asli: [22 28 99 41 50]|

**b.** Seorang engineer ingin melakukan simulasi dengan data temperatur, dan memastikan bahwa perubahan data baru tidak mempengaruhi data aslinya. Buat "deep copy" dari array temperatur dan ubah data salinan tersebut.

In [ ]:
# Data temperatur asli
temp_asli = np.array([[25, 28, 30], [32, 35, 38], [40, 42, 45]])

# Buat deep copy dari temp_asli

# Ubah elemen di baris ke-3, kolom ke-2 temp_copy menjadi 99

# Tampilkan data sesuai contoh output

*Test case* program

|**Input**|**Output**    |
|---------|--------------|
|         |Temperatur Copy:<br> [[25 28 30]<br> [32 35 38]<br> [40 99 45]]<br>Temperatur Asli:<br> [[25 28 30]<br> [32 35 38]<br> [40 42 45]]|

### 9. Operasi Dasar Array (`5`)

**a.** Seorang supervisor ingin mengetahui jumlah produksi tertinggi yang dicapai oleh pabrik dari hasil produksi bulanan. </br> Tambahkan juga kode untuk menghitung selisih antara produksi maksimum dan produksi rata-rata.

In [ ]:
# Data produksi pabrik dalam array
produksi = np.array([1200, 1450, 1100, 1680, 1320])

# Temukan produksi maksimum

# Hitung produksi rata-rata

# Hitung selisih antara produksi maksimum dan rata-rata 

# Tampilkan produksi maksimum dan selisihnya

*Test case* program

|**Input**|**Output**    |
|---------|--------------|
|         |Produksi Maksimum: 1680<br> Selisih Maksimum dan Rata-rata: 330.0|

**b.** Seorang pelatih atletik ingin mengetahui waktu lari tercepat dari setiap atlet. Hitung juga perbedaan waktu antara waktu tercepat dan waktu rata-rata.

In [ ]:
# Data waktu lari atlet (dalam detik)
waktu_lari = np.array([12.5, 11.8, 13.2, 12.1, 11.5])

# Temukan waktu tercepat

# Hitung waktu rata-rata

# Hitung perbedaan waktu tercepat dengan rata-rata

# Tampilkan waktu tercepat dan selisihnya

*Test case* program

|**Input**|**Output**    |
|---------|--------------|
|         |Waktu Tercepat: 11.5<br> Selisih Waktu Tercepat dan Rata-rata: -0.72|

**c.** Dalam sebuah event, seorang panitia ingin mengetahui total pengunjung yang datang selama empat hari acara. Tampilkan rata-rata pengunjung per hari.

In [ ]:
# Data pengunjung event dalam 4 hari
pengunjung_event = np.array([1250, 1480, 1320, 1590])

# Hitung total pengunjung

# Hitung rata-rata pengunjung per hari

# Tampilkan total pengunjung dan rata-ratanya

*Test case* program

|**Input**|**Output**    |
|---------|--------------|
|         |Total Pengunjung: 5640<br> Rata-rata Pengunjung per Hari: 1410.0|

### 10. Transpose dan Reshape Array (`15`)

**a.** Seorang HRD ingin menampilkan data karyawan dalam format yang berbeda. Data saat ini disusun dalam bentuk baris, di mana setiap baris merepresentasikan kategori data. **Anda diminta untuk mengubah array tersebut sehingga data karyawan ditampilkan per kolom.**

In [ ]:
# Data karyawan (Nama, ID, Departemen)
data_karyawan = np.array([['Budi', 'Siti', 'Andi'], ['K001', 'K002', 'K003'], ['IT', 'HR', 'Finance']])

# Ubah data_karyawan

# Tampilkan data karyawan

*Test case* program

|**Input**|**Output**    |
|---------|--------------|
|         |Data karyawan:<br> [['Budi' 'K001' 'IT']<br> ['Siti' 'K002' 'HR']<br> ['Andi' 'K003' 'Finance']]|

In [ ]:
# Data gaji karyawan
gaji = np.array([5000, 6500, 7200, 4800, 5500, 6000, 7500, 8000])

# Bentuk ulang array gaji menjadi 2D dengan 4 kolom

# Tampilkan array gaji

*Test case* program

|**Input**|**Output**    |
|---------|--------------|
|         |Array gaji:<br> [[5000 6500 7200 4800]<br> [5500 6000 7500 8000]]|

**c.** Sebuah toko online ingin menganalisis data order dari berbagai kategori. Data saat ini ada dalam bentuk array 1D. Ubah array tersebut menjadi bentuk 2D dan transposisikan hasilnya agar data kategori dan periode lebih mudah dibaca.

In [ ]:
# Data order: [Kategori A, Kategori B, Kategori A, Kategori B, Kategori A, Kategori B]
order = np.array([85, 92, 78, 88, 95, 81])

# Ubah array 

# Tampilkan data order

*Test case* program

|**Input**|**Output**    |
|---------|--------------|
|         |Data order:<br> [[85 78 95]<br>  [92 88 81]]|

### 11. Soal Cerita (`20`)

Seorang manajer gym sedang menganalisis tingkat kehadiran member (skala 1 - 10) dari empat cabang gym selama 6 minggu. Data kehadiran disimpan dalam sebuah array yang merepresentasikan rating kehadiran dari empat cabang (kolom) di setiap minggu (baris). Manajer hanya tertarik pada minggu-minggu di mana rata-rata kehadiran keempat cabang lebih dari atau sama dengan 7. Mereka ingin menganalisis lebih lanjut dengan menyalin data minggu tersebut, melakukan transpose pada data untuk melihat statistik dari perspektif cabang, dan menghitung rata-rata kehadiran tiap cabang. Berikut adalah langkah-langkah yang perlu dilakukan:

- Ambil subset data dari minggu-minggu yang dimana rata-rata kehadiran 4 cabang pada minggu yang sama memiliki nilai lebih dari atau sama dengan 7
- Buat salinan data untuk dianalisis lebih lanjut
- *Transpose array* hasil salinan statistik
- Ambil rata-rata kehadiran tiap cabang pada minggu (baris) yang terdapat pada subset dari data kehadiran

In [ ]:
# Buat array yang merepresentasikan data kehadiran 6 minggu dari 4 cabang (6x4)
data_kehadiran = np.array([
    [8, 7, 9, 6], 
    [5, 6, 4, 7], 
    [9, 8, 7, 8], 
    [6, 5, 6, 5], 
    [7, 8, 9, 8], 
    [10, 9, 8, 9]
])

# You're on Your Own, Kid. Good Luck :)
None

*Test case* program

|**Input**|**Output**    |
|---------|--------------|
|         |Data Kehadiran Asli:<br>[[ 8  7  9  6]<br>[ 5  6  4  7]<br>[ 9  8  7  8]<br>[ 6  5  6  5]<br>[ 7  8  9  8]<br>[10  9  8  9]]<br>Subset Data Kehadiran:<br>[[ 8  7  9  6]<br>[ 9  8  7  8]<br>[ 7  8  9  8]<br>[10  9  8  9]]<br>Data Setelah Di-transpose:<br>[[ 8  9  7 10]<br>[ 7  8  8  9]<br>[ 9  7  9  8]<br>[ 6  8  8  9]]<br>Rata - Rata Kehadiran Cabang 1:  8.5<br>Rata - Rata Kehadiran Cabang 2:  8.0<br>Rata - Rata Kehadiran Cabang 3:  8.25<br>Rata - Rata Kehadiran Cabang 4:  7.75|